In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

df_train = pd.read_csv(r"D:\Program Files\VSCode project\ML_journey\data\titanic\train.csv")

df_train.info()
df_train.describe()

df_train = df_train.drop(columns="Name")
df_train.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,female,NaN,0,0,2649,7.2250,NaN,C

In [7]:
df_train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [24]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    object
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [8]:
categorical_features = ['Sex', 'Embarked']
numeric_features = ['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
df_train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
from sklearn.impute import SimpleImputer
imp_most_frequent = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
df_train[categorical_features] = imp_most_frequent.fit_transform(df_train[categorical_features])
df_train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [12]:
df_train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [29]:
from sklearn.impute import KNNImputer
impute = KNNImputer(n_neighbors=2, weights="uniform")
df_train[numeric_features] = impute.fit_transform(df_train[numeric_features])
df_train.head(10)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3.0,male,22.0,1.0,0.0,A/5 21171,7.2500,B96 B98,S
1,2,1.0,1.0,female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3,1.0,3.0,female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,B96 B98,S
3,4,1.0,1.0,female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5,0.0,3.0,male,35.0,0.0,0.0,373450,8.0500,B96 B98,S
5,6,0.0,3.0,male,26.5,0.0,0.0,330877,8.4583,B96 B98,Q
6,7,0.0,1.0,male,54.0,0.0,0.0,17463,51.8625,E46,S
7,8,0.0,3.0,male,2.0,3.0,1.0,349909,21.0750,B96 B98,S
8,9,1.0,3.0,female,27.0,0.0,2.0,347742,11.1333,B96 B98,S
9,10,1.0,2.0,female,14.0,1.0,0.0,237736,30.0708,B96 B98,C

In [13]:
df_train[['Sex', 'Cabin', 'Embarked']].nunique()

Sex           2
Cabin       147
Embarked      3
dtype: int64

In [27]:
df_train[df_train['Ticket'].duplicated()]
df_train['Ticket'].duplicated().sum()

np.int64(210)

In [ ]:
def get_cabin(tiket, cabin):
    arr_pass = ['',0] for _ in range(211)]
    for index, (val_t, val_c) in enumerate(zip(tiket, cabin)):
        if val_t not in arr_pass:
            arr_pass[val_t][0] = 

df_train[df_train['Ticket'] == '349909']

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,male,2.0,3,1,349909,21.075,NaN,S
24,25,0,3,female,8.0,3,1,349909,21.075,NaN,S
374,375,0,3,female,3.0,3,1,349909,21.075,NaN,S
567,568,0,3,female,29.0,0,4,349909,21.075,NaN,S

In [21]:
df_train.iloc[889]

PassengerId       890
Survived            1
Pclass              1
Sex              male
Age              26.0
SibSp               0
Parch               0
Ticket         111369
Fare             30.0
Cabin            C148
Embarked            C
Name: 889, dtype: object

In [23]:
from feature_engine.encoding import OneHotEncoder

one = OneHotEncoder(variables=['Sex','Embarked'])

df_train = one.fit_transform(df_train)

ValueError: Some of the variables in the dataset contain NaN. Check and remove those before using this transformer.

In [14]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Sex_male    891 non-null    int64
 1   Sex_female  891 non-null    int64
dtypes: int64(2)
memory usage: 14.1 KB